--CUSTOMERS WHO SPENT THE MOST
SELECT
    c.customer_id,
    c.first_name,
    c.last_name,
    c.country,
    t.total_spent
FROM customer c
JOIN (
    SELECT customer_id,
           SUM(total) AS total_spent
    FROM invoice
    GROUP BY customer_id
) t
ON c.customer_id = t.customer_id
ORDER BY total_spent DESC LIMIT 20;


--AVERAGE CUSTOMER LIFETIME VALUE
SELECT 
    AVG(total_spent) 
    AS avg_customer_lifetime_value
FROM customer 
    JOIN (SELECT customer_id, SUM(total) AS total_spent
          FROM invoice
          GROUP BY customer_id) t
ON customer.customer_id = t.customer_id;


--NUMBER OF PURCHASES PER CUSTOMER
SELECT 
    customer_id,COUNT(*) AS purchase_count
FROM invoice
GROUP BY customer_id
ORDER BY customer_id ASC;    



--REPEAT CUSTOMERS VS ONE-TIME CUSTOMERS
SELECT
    COUNT(*) AS total_customers,
    SUM(CASE WHEN purchase_count > 1 THEN 1 ELSE 0 END) AS repeat_customers,
    SUM(CASE WHEN purchase_count = 1 THEN 1 ELSE 0 END) AS one_time_customers
FROM (
    SELECT customer_id, COUNT(*) AS purchase_count
    FROM invoice
    GROUP BY customer_id
) t;


--USERS PER COUNTRY
SELECT 
    country, COUNT(*) AS user_count
FROM customer
GROUP BY country
ORDER BY user_count DESC;


--REVENUE GENERATED BY EACH COUNTRY
SELECT 
    i.billing_country,
    SUM(i.total) AS total_revenue
FROM invoice i
GROUP BY i.billing_country
ORDER BY total_revenue DESC;


--AVERAGE REVENUE PER CUSTOMER BY COUNTRY
SELECT 
    c.country,
    AVG(t.total_spent) AS avg_revenue_per_customer
FROM customer c
JOIN (
    SELECT customer_id,
           SUM(total) AS total_spent
    FROM invoice
    GROUP BY customer_id
) t
ON c.customer_id = t.customer_id
GROUP BY c.country
ORDER BY avg_revenue_per_customer DESC; 


--AVERAGE INVOICE VALUE PER CUSTOMER
SELECT 
    c.customer_id,
    c.first_name,
    c.last_name,
    AVG(i.total) AS avg_invoice_value
FROM customer c
JOIN invoice i ON c.customer_id = i.customer_id
GROUP BY c.customer_id, c.first_name, c.last_name
ORDER BY avg_invoice_value DESC;


--PEAK MUSIC SALES MONTHS
SELECT
    EXTRACT(MONTH FROM invoice_date) AS month,
    SUM(total) AS total_sales
FROM invoice
GROUP BY month
ORDER BY total_sales DESC;  


--MOST EARNING TRACKS
SELECT
    t.track_id,
    t.name AS track_name,
    SUM(i.total) AS total_earned,
    COUNT(il.track_id) AS purchase_count
FROM invoice i
JOIN invoice_line il ON i.invoice_id = il.invoice_id
JOIN track t ON il.track_id = t.track_id
GROUP BY t.track_id, t.name
ORDER BY total_earned DESC
LIMIT 20;


--TRACKS PER GENRE
SELECT
    g.name AS genre_name,
    COUNT(t.track_id) AS track_count
FROM genre g
JOIN track t ON g.genre_id = t.genre_id
GROUP BY g.genre_id, g.name
ORDER BY track_count DESC;  


--UNSOLD TRACKS
SELECT
    t.track_id,
    t.name AS track_name,
    g.name AS genre_name,
FROM track t
JOIN genre g ON t.genre_id = g.genre_id
LEFT JOIN invoice_line il ON t.track_id = il.track_id
WHERE il.invoice_line_id IS NULL
ORDER BY t.track_id ASC;
   

--TOP ARTISTS BY SALES
SELECT
    a.artist_id,
    a.name AS artist_name,
    SUM(i.total) AS total_sales
FROM artist a
JOIN album al ON a.artist_id = al.artist_id
JOIN track t ON al.album_id = t.album_id
JOIN invoice_line il ON t.track_id = il.track_id
JOIN invoice i ON il.invoice_id = i.invoice_id
GROUP BY a.artist_id, a.name
ORDER BY total_sales DESC
LIMIT 20;   


-- MOST POPULAR GENRES IN EACH COUNTRY
SELECT 
    country, genre_name, purchase_count
FROM (
    SELECT
        c.country,
        g.name AS genre_name,
        COUNT(il.track_id) AS purchase_count,
        RANK() OVER (
            PARTITION BY c.country
            ORDER BY COUNT(il.track_id) DESC
        ) AS rnk
    FROM customer c
    JOIN invoice i ON c.customer_id = i.customer_id
    JOIN invoice_line il ON i.invoice_id = il.invoice_id
    JOIN track t ON il.track_id = t.track_id
    JOIN genre g ON t.genre_id = g.genre_id
    GROUP BY c.country, g.name
) x
WHERE rnk = 1;


--EMPLOYEES WITH THE HIGHEST SALES
SELECT
    e.employee_id,
    e.first_name,
    e.last_name,
    SUM(i.total) AS total_sales
FROM employee e
JOIN customer c ON e.employee_id = c.support_rep_id
JOIN invoice i ON c.customer_id = i.customer_id
GROUP BY e.employee_id, e.first_name, e.last_name
ORDER BY total_sales DESC
LIMIT 20;


--HIGHEST PAYING CUSTOMERS AND THEIR SUPPORT REPS
SELECT
    c.customer_id AS customer_id,
    c.first_name AS customer_first_name,
    c.last_name AS customer_last_name,
    c.support_rep_id AS employee_id,
    e.first_name AS employee_first_name,
    e.last_name AS employee_last_name,
    SUM(i.total) AS total_spent
FROM customer c
JOIN invoice i ON c.customer_id = i.customer_id
JOIN employee e ON c.support_rep_id = e.employee_id
GROUP BY c.customer_id, c.first_name, c.last_name, c.support_rep_id, e.first_name, e.last_name
ORDER BY total_spent DESC
LIMIT 20;


--NUMBER OF CUSTOMERS PER SUPPORT REP
SELECT
    e.employee_id,
    e.first_name,
    e.last_name,
    COUNT(c.customer_id) AS customer_count
FROM employee e
LEFT JOIN customer c ON e.employee_id = c.support_rep_id
GROUP BY e.employee_id, e.first_name, e.last_name
ORDER BY customer_count DESC;   


--CUSTOMERS WITH MORE THAN 1 GENRE PURCHASE
SELECT
    c.customer_id,
    c.first_name,
    c.last_name,
    COUNT(DISTINCT g.genre_id) AS genre_count
FROM customer c
JOIN invoice i ON c.customer_id = i.customer_id
JOIN invoice_line il ON i.invoice_id = il.invoice_id
JOIN track t ON il.track_id = t.track_id
JOIN genre g ON t.genre_id = g.genre_id
GROUP BY c.customer_id, c.first_name, c.last_name
HAVING COUNT(DISTINCT g.genre_id) > 1
ORDER BY genre_count DESC;


--MOST USED MEDIA TYPES
SELECT
    mt.name AS media_type,
    COUNT(t.track_id) AS track_count
FROM media_type mt
JOIN track t ON mt.media_type_id = t.media_type_id
GROUP BY mt.media_type_id, mt.name
ORDER BY track_count DESC;


--MOST PURCHASED TRACK COMBINATIONS
SELECT
    t1.name AS track1,
    t2.name AS track2,
    COUNT(*) AS purchase_count
FROM invoice_line il1
JOIN invoice_line il2 ON il1.invoice_id = il2.invoice_id AND il1.invoice_line_id < il2.invoice_line_id
JOIN track t1 ON il1.track_id = t1.track_id
JOIN track t2 ON il2.track_id = t2.track_id
GROUP BY t1.name, t2.name
ORDER BY purchase_count DESC
LIMIT 20;


--AMOUNT OF SALES PER ARTIST
SELECT
    a.name AS artist_name,
    SUM(i.total) AS total_sales
FROM artist a
JOIN album al ON a.artist_id = al.artist_id
JOIN track t ON al.album_id = t.album_id
JOIN invoice_line il ON t.track_id = il.track_id
JOIN invoice i ON il.invoice_id = i.invoice_id
GROUP BY a.artist_id, a.name
ORDER BY total_sales DESC
LIMIT 20;


--ARTISTS WITH THE MOST DIVERSE GENRES
SELECT
    a.name AS artist_name,
    COUNT(DISTINCT g.genre_id) AS genre_count
FROM artist a
JOIN album al ON a.artist_id = al.artist_id
JOIN track t ON al.album_id = t.album_id
JOIN genre g ON t.genre_id = g.genre_id
GROUP BY a.artist_id, a.name
ORDER BY genre_count DESC
LIMIT 20;


--ROCK GENRE CUSTOMERS
SELECT
    c.customer_id,
    c.first_name,
    c.last_name,
    c.email,
    COUNT(*) AS rock_purchase_count
FROM customer c
JOIN invoice i ON c.customer_id = i.customer_id
JOIN invoice_line il ON i.invoice_id = il.invoice_id
JOIN track t ON il.track_id = t.track_id
JOIN genre g ON t.genre_id = g.genre_id
WHERE g.name = 'Rock'
GROUP BY c.customer_id, c.first_name, c.last_name
ORDER BY rock_purchase_count DESC;


-- CITY WITH THE MOST CUSTOMERS AND ITS MOST POPULAR GENRE
SELECT
    x.city,
    x.genre_name,
    x.genre_purchase_count
FROM (
    SELECT
        c.city,
        g.name AS genre_name,
        COUNT(il.track_id) AS genre_purchase_count,
        RANK() OVER (
            ORDER BY COUNT(il.track_id) DESC  -- Step 2: rank genres by purchases
        ) AS genre_rnk
    FROM customer c
    JOIN invoice i ON c.customer_id = i.customer_id
    JOIN invoice_line il ON i.invoice_id = il.invoice_id
    JOIN track t ON il.track_id = t.track_id
    JOIN genre g ON t.genre_id = g.genre_id
    WHERE c.city = (
        -- Step 1: find the single city with the most customers
        SELECT city
        FROM customer
        GROUP BY city
        ORDER BY COUNT(DISTINCT customer_id) DESC
        LIMIT 1
    )
    GROUP BY c.city, g.name
) x
WHERE x.genre_rnk = 1;